// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/google": {
            "post": {
                "description": "Authenticate using Google ID Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Google Login",
                "parameters": [
                    {
                        "description": "Google ID Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Login using Email and Password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Local Account Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current account information via JWT Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Account Information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "description": "Register a new user using Email and Password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Local Account Signup",
                "parameters": [
                    {
                        "description": "Signup information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cashflow/dependents": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Get all dependents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Dependent"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Create a dependent",
                "parameters": [
                    {
                        "description": "Dependent info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateDependentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Dependent"
                        }
                    }
                }
            }
        },
        "/api/v1/cashflow/dependents/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Update a dependent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dependent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dependent info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateDependentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Dependent"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Delete a dependent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dependent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/cashflow/income": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Get all income streams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.IncomeStream"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Create an income stream",
                "parameters": [
                    {
                        "description": "Income Stream info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateIncomeStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.IncomeStream"
                        }
                    }
                }
            }
        },
        "/api/v1/cashflow/income/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Update an income stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Income ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Income Stream info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateIncomeStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.IncomeStream"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Cashflow"
                ],
                "summary": "Delete an income stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Income ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Check backend health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/profile/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current active investor profile for the logged in user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Active Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.InvestorProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the current active investor profile for the logged in user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update Active Profile",
                "parameters": [
                    {
                        "description": "Profile Update Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.InvestorProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/profile/onboarding": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit the 8-step chat history to let AI analyze and create an Investor Profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Submit AI Onboarding Interview",
                "parameters": [
                    {
                        "description": "Chat history data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OnboardingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.InvestorProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/profile/timeline": {
            "get": {
                "description": "Retrieve a list of all life events logged by the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeline"
                ],
                "summary": "Get user's life timeline",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.LifeEvent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/profile/timeline/analyze": {
            "post": {
                "description": "Send event text to AI to analyze its impact on the user's financial profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeline"
                ],
                "summary": "Analyze a new life event",
                "parameters": [
                    {
                        "description": "Event Text",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LogEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ai.LifeEventAnalysisResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/profile/timeline/confirm": {
            "post": {
                "description": "Apply the analyzed (and potentially edited) life event to the database, cascading profile changes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeline"
                ],
                "summary": "Confirm and save a life event",
                "parameters": [
                    {
                        "description": "Event Confirmation",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfirmEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/wealth/assets": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Get all assets for current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category filter",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PaginatedAssets"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Create a new asset",
                "parameters": [
                    {
                        "description": "Asset info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Asset"
                        }
                    }
                }
            }
        },
        "/api/v1/wealth/assets/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Update an asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Asset"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Delete an asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/wealth/liabilities": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Get all liabilities for current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category filter",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PaginatedLiabilities"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Create a new liability",
                "parameters": [
                    {
                        "description": "Liability info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateLiabilityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Liability"
                        }
                    }
                }
            }
        },
        "/api/v1/wealth/liabilities/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Update a liability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Liability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Liability info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateLiabilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Liability"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Delete a liability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Liability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/wealth/net-worth": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get total assets, total liabilities and net worth for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wealth"
                ],
                "summary": "Get net worth summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.NetWorthSummary"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ai.DependentDraft": {
            "type": "object",
            "properties": {
                "monthly_cost": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "relationship": {
                    "type": "string"
                }
            }
        },
        "ai.IncomeStreamDraft": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "ai.LifeEventAnalysisResult": {
            "type": "object",
            "properties": {
                "ai_impact_analysis": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "dependents_to_add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.DependentDraft"
                    }
                },
                "expense_impact": {
                    "type": "number"
                },
                "income_impact": {
                    "type": "number"
                },
                "income_streams_to_add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.IncomeStreamDraft"
                    }
                },
                "new_marital_status": {
                    "type": "string"
                },
                "new_risk_score": {
                    "type": "integer"
                },
                "new_risk_tolerance": {
                    "type": "string"
                }
            }
        },
        "model.Asset": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "category": {
                    "$ref": "#/definitions/model.AssetCategory"
                },
                "cost_basis": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "current_price": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.AssetCategory": {
            "type": "string",
            "enum": [
                "cash",
                "deposit",
                "gold",
                "stock",
                "fund",
                "crypto",
                "real_estate"
            ],
            "x-enum-varnames": [
                "AssetCategoryCash",
                "AssetCategoryDeposit",
                "AssetCategoryGold",
                "AssetCategoryStock",
                "AssetCategoryFund",
                "AssetCategoryCrypto",
                "AssetCategoryRealEstate"
            ]
        },
        "model.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "The text content",
                    "type": "string"
                },
                "role": {
                    "description": "\"user\" or \"assistant\"",
                    "type": "string"
                }
            }
        },
        "model.ConfirmEventRequest": {
            "type": "object",
            "properties": {
                "ai_impact_analysis": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "dependents_to_add": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "monthly_cost": {
                                "type": "number"
                            },
                            "name": {
                                "type": "string"
                            },
                            "relationship": {
                                "type": "string"
                            }
                        }
                    }
                },
                "event_text": {
                    "type": "string"
                },
                "expense_impact": {
                    "type": "number"
                },
                "income_impact": {
                    "type": "number"
                },
                "income_streams_to_add": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "amount": {
                                "type": "number"
                            },
                            "is_passive": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            }
                        }
                    }
                },
                "new_marital_status": {
                    "type": "string"
                },
                "new_risk_score": {
                    "type": "integer"
                },
                "new_risk_tolerance": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.CreateAssetRequest": {
            "type": "object",
            "required": [
                "category",
                "current_value",
                "name"
            ],
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "category": {
                    "$ref": "#/definitions/model.AssetCategory"
                },
                "cost_basis": {
                    "type": "number"
                },
                "current_price": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "model.CreateDependentRequest": {
            "type": "object",
            "required": [
                "name",
                "relationship"
            ],
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "monthly_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "relationship": {
                    "type": "string"
                }
            }
        },
        "model.CreateIncomeStreamRequest": {
            "type": "object",
            "required": [
                "amount",
                "name",
                "type"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "frequency": {
                    "description": "e.g., \"monthly\", \"yearly\"",
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.CreateLiabilityRequest": {
            "type": "object",
            "required": [
                "category",
                "name",
                "remaining_balance"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/model.LiabilityCategory"
                },
                "interest_rate": {
                    "type": "number"
                },
                "lender": {
                    "type": "string"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "remaining_balance": {
                    "type": "number"
                }
            }
        },
        "model.Dependent": {
            "type": "object",
            "properties": {
                "added_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "monthly_cost": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "relationship": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.GoogleLoginRequest": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "model.IncomeStream": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.InvestorProfile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "discretionary_monthly_expense": {
                    "type": "number"
                },
                "essential_monthly_expense": {
                    "type": "number"
                },
                "fi_target_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "marital_status": {
                    "type": "string"
                },
                "risk_score": {
                    "type": "integer"
                },
                "risk_tolerance": {
                    "type": "string"
                },
                "status": {
                    "description": "active, superseded",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "model.Liability": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/model.LiabilityCategory"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interest_rate": {
                    "type": "number"
                },
                "is_active": {
                    "type": "boolean"
                },
                "lender": {
                    "type": "string"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "remaining_balance": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.LiabilityCategory": {
            "type": "string",
            "enum": [
                "mortgage",
                "auto_loan",
                "student_loan",
                "credit_card",
                "personal_loan",
                "other"
            ],
            "x-enum-varnames": [
                "LiabilityCategoryMortgage",
                "LiabilityCategoryAutoLoan",
                "LiabilityCategoryStudentLoan",
                "LiabilityCategoryCreditCard",
                "LiabilityCategoryPersonalLoan",
                "LiabilityCategoryOther"
            ]
        },
        "model.LifeEvent": {
            "type": "object",
            "properties": {
                "ai_impact_analysis": {
                    "type": "string"
                },
                "category": {
                    "description": "Uses life_event_category enum",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "event_date": {
                    "type": "string"
                },
                "expense_impact": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "income_impact": {
                    "type": "number"
                },
                "requires_ips_update": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "triggered_ips_version": {
                    "type": "integer"
                },
                "triggered_profile_version": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.LogEventRequest": {
            "type": "object",
            "properties": {
                "event_text": {
                    "type": "string"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.NetWorthSummary": {
            "type": "object",
            "properties": {
                "base_currency": {
                    "type": "string"
                },
                "net_worth": {
                    "type": "number"
                },
                "total_assets": {
                    "type": "number"
                },
                "total_liabilities": {
                    "type": "number"
                }
            }
        },
        "model.OnboardingRequest": {
            "type": "object",
            "properties": {
                "chat_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChatMessage"
                    }
                }
            }
        },
        "model.PaginatedAssets": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Asset"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "model.PaginatedLiabilities": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Liability"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "model.SignupRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "model.UpdateAssetRequest": {
            "type": "object",
            "required": [
                "category",
                "current_value",
                "name"
            ],
            "properties": {
                "avg_price": {
                    "type": "number"
                },
                "category": {
                    "$ref": "#/definitions/model.AssetCategory"
                },
                "cost_basis": {
                    "type": "number"
                },
                "current_price": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "model.UpdateDependentRequest": {
            "type": "object",
            "required": [
                "name",
                "relationship"
            ],
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "monthly_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "relationship": {
                    "type": "string"
                }
            }
        },
        "model.UpdateIncomeStreamRequest": {
            "type": "object",
            "required": [
                "amount",
                "name",
                "type"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "frequency": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateLiabilityRequest": {
            "type": "object",
            "required": [
                "category",
                "name",
                "remaining_balance"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/model.LiabilityCategory"
                },
                "interest_rate": {
                    "type": "number"
                },
                "lender": {
                    "type": "string"
                },
                "monthly_payment": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "remaining_balance": {
                    "type": "number"
                }
            }
        },
        "model.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "discretionary_monthly_expense": {
                    "type": "number"
                },
                "essential_monthly_expense": {
                    "type": "number"
                },
                "fi_target_amount": {
                    "type": "number"
                },
                "marital_status": {
                    "type": "string"
                },
                "risk_score": {
                    "type": "integer"
                },
                "risk_tolerance": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "auth_provider": {
                    "type": "string"
                },
                "base_currency": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Life Capital (WealthOS) API",
	Description:      "API server for Personal Wealth Operating System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
